### ISSUE TITLE
[Help] Extra Embed Builder Fields

### ISSUE THREAD

**Issue by Frankie813** [nwilging/laravel-discord-bot#9]
Hi there, 

I'm trying to add title, description, and color fields to my embedded message in notifications but I just cannot wrap my head around it. 

Is there a way to add title, description, and color to the embed builder?

Thanks!

**Comment by nwilging** [comment]
The embed builder offers a way to build the various [embed types](https://discord.com/developers/docs/resources/channel#embed-object-embed-types). Discord requires embed objects to have a `type`, and therefore the generic `Nwilging\LaravelDiscordBot\Support\Embed` object (which is an abstract class) is _not_ a valid embed object.

What you'll be looking to do is create one of the available embed types: image, video, gif, article, etc. All embeds support the title, description, and color attributes.

Using the `EmbedBuilder`, you can sometimes lose the ability to specify additional attributes (since the builder takes just the default required args). Therefore you'd want to instantiate a new embed object, do something with it, then add it to an embed builder (if you want to use the embed builder).

For example, creating a rich text embed:
```
use Nwilging\LaravelDiscordBot\Support\Embeds\GenericEmbed;
use Nwilging\LaravelDiscordBot\Support\Builder\EmbedBuilder;

$builder = new EmbedBuilder();

$embed = new GenericEmbed('title', 'description');
$embed->withColor(<color code>);

$builder->addEmbed($embed);

$output = $builder->toArray();
```

The same is technically possible using the `addEmbed` method of the builder:
```
$builder = new EmbedBuilder();

$builder->addEmbed((new GenericEmbed('title', 'description'))->withColor(<color code>));
```

Titles and descriptions should always be specified in the embed object's constructor.

**Comment by Dennion** [comment]
Heyho,

how works the FieldEmbed? I want to have a Embed with title, description, url and 5 fields. 
My Code: 
`$embedBuilder = new EmbedBuilder();
        $geneticEmbed = new GenericEmbed('⚠️ Report ⚠️', 'Report');
        $embedBuilder->addEmbed($geneticEmbed);
        $field1 = new FieldEmbed('Comment', $this->comment, 'Comment');
        $embedBuilder->addEmbed($field1);
        $embedBuilder->addEmbed(new FieldEmbed('message', $this->message, 'Message'));
        Log::debug($embedBuilder->getEmbeds());`

but the Result:
`[2023-04-18 20:17:52] local.DEBUG: array (
  0 => 
  \Nwilging\LaravelDiscordBot\Support\Embeds\GenericEmbed::__set_state(array(
     'title' => '⚠️ Report ⚠️',
     'description' => 'Report',
     'timestamp' => NULL,
     'color' => NULL,
  )),
  1 => 
  \Nwilging\LaravelDiscordBot\Support\Embeds\FieldEmbed::__set_state(array(
     'title' => 'Comment',
     'description' => NULL,
     'timestamp' => NULL,
     'color' => NULL,
     'name' => 'Comment',
     'value' => 'asdasdasd',
     'inline' => NULL,
  )),
  2 => 
  \Nwilging\LaravelDiscordBot\Support\Embeds\FieldEmbed::__set_state(array(
     'title' => 'Message',
     'description' => NULL,
     'timestamp' => NULL,
     'color' => NULL,
     'name' => 'message',
     'value' => 'Ein Beitrag wurde gemeldet',
     'inline' => NULL,
  )),
`

who it works?

Greets,
Dennion

**Comment by nwilging** [comment]
@Dennion please open a new issue with more detail regarding your specific problem
